### ISSUE TITLE
Automatic configuration of DHCP makes NAT networks with multiple prefixes unusable

### ISSUE THREAD

**Issue by pdf** [dmacvicar/terraform-provider-libvirt#274]
#  Version Reports:

### Distro  version of host:

`Arch`

### Terraform Version Report

`v0.11.2`

### Libvirt version

`3.10.0`

### terraform-provider-libvirt plugin version (git-hash)

`29cd517335347ed7a8b190e60664887a9b715f09`
___
# Description of Issue/Question

### Setup

```
resource "libvirt_network" "terraform" {
  name      = "terraform"
  domain    = "terraform.local"
  mode      = "nat"
  addresses = ["192.168.123.0/24", "172.16.100.0/24"]
}
```

### Steps to Reproduce Issue

Attempt to apply the above resource results in:

```
Error: Error applying plan:

1 error(s) occurred:

* module.infra.module.libvirt.libvirt_network.terraform: 1 error(s) occurred:

* libvirt_network.terraform: Error defining libvirt network: virError(Code=67, Domain=19, Message='unsupported configuration: Multiple IPv4 dhcp sections found -- dhcp is supported only for a single IPv4 address on each network') -   <network>
      <name>terraform</name>
      <bridge stp="on"></bridge>
      <forward mode="nat"></forward>
      <domain name="terraform.local"></domain>
      <ip address="192.168.123.1" family="ipv4" prefix="24">
          <dhcp>
              <range start="192.168.123.2" end="192.168.123.254"></range>
          </dhcp>
      </ip>
      <ip address="172.16.100.1" family="ipv4" prefix="24">
          <dhcp>
              <range start="172.16.100.2" end="172.16.100.254"></range>
          </dhcp>
      </ip>
  </network>
```

___

**Comment by inercia** [comment]
The original intention of having multiple IP ranges was to provide IPv4 as well as IPv6 addresses for the network, as multiple IPv4 addresses do not make much sense (at least for regular users). So this is the expected behaviour, even when we are getting the error from the lower layers of the stack (libvirt).

We could 1) improve documentation and/or 2) do some checks at the terraform-libvirt-provider layer.

**Comment by inercia** [comment]
It seems it is properly documented [here](https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/network.markdown), and the checks at the `terraform-libvirt-provider` layer would be a _nice-to-have_ feature but not strictly necessary...

**Comment by pdf** [comment]
> The original intention of having multiple IP ranges was to provide IPv4 as well as IPv6 addresses for the network

From an API point of view, these should probably have been two separate string fields then.

> multiple IPv4 addresses do not make much sense (at least for regular users)

What is a 'regular user'? I need multiple IP address ranges to replicate a production environment.

> We could 1) improve documentation and/or 2) do some checks at the terraform-libvirt-provider layer.

Or:
3) Allow an address range to be configured without enabling DHCP on it?
4) Provide a structure for configuring DHCP properties for an address range?

---

I don't wish to sound rude, but I'm rather baffled by your attitude towards handling issues on this project, which seems to be that if the project supports whatever precise subset of features you personally require, nothing else is relevant, and issues relating to such features are closed out-of-hand.

Is this the case? Should we not bother reporting issues here and just have everyone work on their own forks to support anything that's not required by your downstream?  That sounds rather painful for any users trying to work out what to do, but if this is the case, it should probably be explicitly documented in the README.

**Comment by inercia** [comment]
> 3) Allow an address range to be configured without enabling DHCP on it?

You don't need to configure address ranges if you are not going to use DHCP. Just do not specify `addresses` and DHCP will not be started, so you can configure your interfaces statically in some other way (ie, with `cloud-init`).

> 4) Provide a structure for configuring DHCP properties for an address range?

What kind of properties are you interested in? [These are the properties for addresses](https://libvirt.org/formatnetwork.html#elementsAddress) that libvirt supports.

I've closed this issue because it is not a bug (as it conforms to the specifications found in our documentation) but a feature request. `libvirt` provides a huge number of configuration options, but 1) we try to keep the provider syntax simple, and that means that we cannot expose all of those options, and 2) we have limited resources, so we have to prioritize what we want to implement.

I'm sure some other users will be interested in, for example, specifying NUMA topologies as [libvirt supports it](https://libvirt.org/formatdomain.html#elementsCPU), but we don't want to end up with a unintelligible syntax. And even when there will always be a good reason for exposing those things, _regular users_ do not use NUMA topologies...

If you need some feature that is not present in this provider, I would suggest 1) to fill out an issue specifying your feature request 2) discuss things like the proposed syntax, implementation, etc 3) submit a PR implementing it.

**Comment by pdf** [comment]
> I think you don't need to configure address ranges if you are not going to use DHCP. Just try to not specify addresses and I think DHCP will not be started, so you can configure your interfaces statically in some other way (ie, with cloud-init).

It is not valid to define a NAT network (at least, I suspect some other types may be similarly restricted) without specifying address ranges.  Additionally, libvirt applies iptables rules to the bridge device to ensure that only configured address ranges will pass traffic through the bridge, so it's not possible to use statically configured address ranges without specifying them in the network definition.

> What kind of properties are you interested in?

I'm really only interested in being able to disable configuration of dhcp for a range, my thought was that a separate DHCP stanza might be a way to achieve this without breaking changes (though it may not be the most intuitive).

> *regular users* do not use NUMA topologies

The assertion that it's possible to determine with confidence what a *regular user* is or might want still troubles me, though I don't think multiple IP address ranges are in the same category as NUMA topologies.

> If you need some feature that is not present in this provider, I would suggest 1) to fill out an issue specifying your feature request 2) discuss things like the proposed syntax, implementation, etc 3) submit a PR implementing it.

Do I need to file a new issue?  As it may not have been clear - the implication from the initial report here was that I would like to configure multiple address ranges, however multiple address ranges cannot currently be configured, since all ranges enable DHCP.

I need to maintain a fork anyway, since my last PR to allow IP addresses to be output/consumed from modules was rejected (as it is only necessary due to upstream bugs, and apparently you don't feel the need to support modules in the foreseeable future), however I'm happy to submit code for this if there's some guidance as to what might be accepted.
