### ISSUE TITLE
Using Multiple Providers Fails to copy userdata.iso to all hosts

### ISSUE THREAD

**Issue by cbluth** [dmacvicar/terraform-provider-libvirt#300]
#  Version Reports:

### Distro  version of host:

``` Ubuntu 18.04 ```

### Terraform Version Report
```Terraform v0.11.7```

### Libvirt version

```4.0.0```

### terraform-provider-libvirt plugin version (git-hash)

``` latest ```
___
# Description of Issue/Question

### Setup
Any setup that uses multiple libvirt providers.

### Steps to Reproduce Issue
terraform apply

___
# Additional Infos:
userdata.iso gets copied to one random host, not all hosts as defined in the terraform code.

**Comment by MalloZup** [comment]
@cbluth  ciao! thank you for your issue.

i think this issue is a sub-issue of this one https://github.com/dmacvicar/terraform-provider-libvirt/issues/290

If you agree we can close this and it will referenced on that card. ( for us having less issue can help to focus on tasks)

What do you think? tia :+1:

**Comment by cbluth** [comment]
sounds good

**Comment by MalloZup** [comment]
@cbluth thx! :+1:
