### ISSUE TITLE
template_file user_data containing a tab: terraform plan forces new resource

### ISSUE THREAD

**Issue by marcindulak** [dmacvicar/terraform-provider-libvirt#313]
#  Version Reports:

### Distro  version of host:

```
cat /etc/*release | grep PRETTY_NAME
PRETTY_NAME="Ubuntu 16.04.4 LTS"
```

### Terraform Version Report

```
terraform --version
Terraform v0.11.7
+ provider.libvirt (unversioned)
+ provider.template v1.0.0
```

### Libvirt version

```
virsh --version
1.3.1
```

```
echo $CGO_ENABLED
1
```

### terraform-provider-libvirt plugin version (git-hash)

https://github.com/dmacvicar/terraform-provider-libvirt/commit/b11e5b79ff40dc8f03d762d92226fabe315955dc

___
# Description of Issue/Question

This could possibly be a problem with `terraform` on not the `terraform-provider-libvirt`.

The default example https://github.com/dmacvicar/terraform-provider-libvirt/blob/21c507a4c44b510196b8a4a527aca921e9cd9b11/examples/ubuntu/ubuntu-example.tf is modified due to https://github.com/dmacvicar/terraform-provider-libvirt/issues/311, and uses `template_file`

```
cat ubuntu-example.tf
# instance the provider
provider "libvirt" {
  uri = "qemu:///system"

data "template_file" "user_data" {
  template = "${file("${path.module}/cloud_init.cfg")}"
  #template = "${trimspace("${file("${path.module}/cloud_init.cfg")}")}"

}

# Use CloudInit to add our ssh-key to the instance
resource "libvirt_cloudinit" "commoninit" {
          name           = "commoninit.iso"
	  user_data          = "${data.template_file.user_data.rendered}"
          ssh_authorized_key = ""
        }

```

```
cat cloud_init.cfg 
#cloud-config
ssh_authorized_keys: []
write_files:
- content: |
    #I'm a	tab
```

```
TF_LOG=debug terraform apply -auto-approve
TF_LOG=debug terraform plan
...
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

2018/06/29 19:50:38 [DEBUG] plugin: waiting for all plugin processes to complete...
-/+ libvirt_cloudinit.commoninit (new resource required)
      id:        "/var/lib/libvirt/images/commoninit.iso;5b36712e-d554-ab48-551a-fefc7cdd9f2b" => <computed> (forces new resource)
      name:      "commoninit.iso" => "commoninit.iso"
      pool:      "default" => "default"
      user_data: "#cloud-config\nssh_authorized_keys: []\nwrite_files:\n- content: \"#I'm a\\ttab\\n\"\n" => "#cloud-config\nssh_authorized_keys: []\nwrite_files:\n- content: |\n    #I'm a\ttab\n" (forces new resource)

  ~ libvirt_domain.domain-ubuntu
      cloudinit: "/var/lib/libvirt/images/commoninit.iso;5b36712e-d554-ab48-551a-fefc7cdd9f2b" => "${libvirt_cloudinit.commoninit.id}"


Plan: 1 to add, 1 to change, 1 to destroy.
```

Replace the tab in ` #I'm a	tab` by a space and the plan ends correctly `No changes. Infrastructure is up-to-date.`.

**Comment by night199uk** [comment]
I ran into this aswell while working on #270 and #267.

The problem is a bit complex, so I'll explain as best I can for other devs looking into this:
user_data is actually a computed field. It is the result of merging ssh_authorized_keys with anything specified directly in the raw user_data field and that is what is set into the created cloud_init file. When reading back the cloud_init file, UserDataRaw != the cloud_init UserData.

I initially came up with a fix setting user_data to Computed: True and using StateFunc/ValidationFunc. However this is not perfect either. Because Computed: True only applies when a field is not directly specified in config, and StateFunc does not have access to merge ssh_authorized_keys; if you specify both ssh_authorized_keys and user_data you still get the same result.

My conclusion, without getting into something much more complex (my go is not so hot) is that ssh_authorized_keys should be set as:
 				ConflictsWith: []string{"user_data"},
And then you should specify EITHER ssh_authorized_keys, or raw user_data, but not both. In this case the merge strategy for user_data can be simplified.

**Comment by marcindulak** [comment]
Let's not forget this issue is about a tab vs. space in the cloud init file, which could be a separate issue from merging of `user_data` with `ssh_authorized_key`. Having to specify EITHER use `ssh_authorized_key` (or `ssh_authorized_keys` - note that the code currently accepts `ssh_authorized_key` as a string), or user_data sounds like a good solution to the latter issue.

**Comment by MalloZup** [comment]
Thx for issue and beeing so accurate +1

**Comment by night199uk** [comment]
@marcindulak: the space vs tab is caused by the same thing. The cloud data you specify is post-processed to perform the merge. That post processing - converting text to yaml, merging ssh keys, and converting yaml back to text, then finally storing the post processed text in the state - that’s what causes the issue you as your spaces are converted to tabs or vice versa.

**Comment by MalloZup** [comment]
@marcindulak i just took the freedom to make less verbose your TF for reproducing it
@night199uk  thx for your sharing,  `ConflictsWith: []string{"user_data"},` will not work either i just tried it out.

To me after some small research we need to dive better on the `user_data` implementation, is pretty weird at moment that doing a terraform plan mark the resource to be recreated.

I think we need to come up with a better implementation instead of using some terraform helper functoin that would modify the behaviour but not the root cause. 
@ianabc  atm this is known issue so you are not doing something wrong :+1:  thx for feedback

**Comment by MalloZup** [comment]
ciao all, i create a PR for this in WIP were we will delegate everything to cloud_init files.

This is the most cleanest solution

**Comment by MalloZup** [comment]
this is now fixed on latest version.

@marcindulak @night199uk @ianabc 

you can have a look on the example : 

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/examples/ubuntu/ubuntu-example.tf

So basically this bug is gone :+1: have fun and keep doing opensource :sun_with_face: :tulip:
