### ISSUE TITLE
Research on better implementation of cloudinit 

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#384]
https://www.terraform.io/docs/providers/template/d/cloudinit_config.html

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/issues/313 and many other issues. Goal of this is to be spare code more generic

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/267

**Comment by multani** [comment]
One issue that is a bit painful with current implementation is that the user data is rewritten before being saved in the state: if the original content (the one written in the Terraform configuration) differs from the one saved in the state due to the rewritting, Terraform will decide to recreate the cloud-init resource and its dependencies.

To prevent this, we have to take care of writing in our Terraform configuration a user data field which will contain the exact same order/content (the best we could!) as the one which will be saved in the state. This is a bit counter intuitive (and bit of an annoyance at the same time :/)

I'm not sure the `libvirt_cloudinit` resource needs to provide the `local_hostname` and `ssh_authorized_key`: it's nice if you are only interested by these but as soon as you have a custom user data, this falls apart and it becomes difficult to manage correctly.

**Comment by MalloZup** [comment]
Yop i agree, that was the motivator for this issue

**Comment by MalloZup** [comment]
fixed ! thx
