### ISSUE TITLE
Block device not supported

### ISSUE THREAD

**Issue by Vanuan** [dmacvicar/terraform-provider-libvirt#418]
#  Version Reports:

### Distro  version of host:

``` Ubuntu 18.04 ```

### Terraform Version Report
(Provided by running `v0.11.8`.)

### Libvirt version

```4.0.0```

### terraform-provider-libvirt plugin version (git-hash)

```terraform-provider-libvirt-0.4.4.Ubuntu_18.04.amd64.tar.gz```
___
# Description of Issue/Question

Reading documentation I can't find a way to attach disk from block device.
I'm looking for an equivalent of:

```virsh attach-disk storageVM /dev/disk/by-id/ata-HGST_HUSXXX sdb```

I've tried this:

```
resource "libvirt_domain" "test" {
  name = "storageVM"
  memory = "1024"
  vcpu = 1

  disk {
    file = "/dev/disk/by-id/ata-HGST_HUSXXX"
    scsi = true
  }

}
```

Doesn't work. Here's a relevant xml snippet returned from dumpxml:

```
...
    <disk type='block' device='disk'>
      <driver name='qemu' type='raw'/>
      <source dev='/dev/disk/by-id/ata-HGST_HUSXXX'/>
      <backingStore/>
      <target dev='sdb' bus='scsi'/>
      <alias name='scsi0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
...
```

**Comment by MalloZup** [comment]
@Vanuan thx for issue. 

If you want to add it and contribute i can help through the code.

Otherwise , yop it is at moment a missing feature that we might add.

Atm we plan 2 prs for next releases, and other things.

To me  i can have a look once i am finished with my tasks.

For any info feel free to ask thx! :sunflower:

**Comment by dmacvicar** [comment]
Quickly thinking about it probably we need to add `device` like we have `file` and `source` (the last being unrelated to libvirt `source` xml block).

**Comment by Vanuan** [comment]
Attach disk required domain, device and target.
It looks like disk def needs to be extended with `diskDef.Source.Block` type.
And target is better be specified.

So something like this would be most intuitive:
```
resource "libvirt_domain" "local-domain" {
  ...
  disk {
    device = "/dev/disk/by-id/ata-HGST_HUSXXX"
    target = "hda"
    scsi = true
  }
  disk {
    device = "/dev/disk/by-id/ata-HGST_HUSYYY"
    target = "hdb"
    scsi = true
  }
  ...
}
```

at least to me. But can there be multiple disk definitions?

**Comment by dmacvicar** [comment]
We always end in the disjunctive of either providing something usable, with a bit of more added value (eg. automatic download of images from the web) at the cost of some advanced features, or a 1:1 mapping of libvirt _xml_  into _hcl_, which would make the definitions very complicated, but all features would be exposed. Until now we have followed the first, and we intentionally do not expose all libvirt features.

 I am not sure how to proceed in this case. I would probably be in favour of adding `device` as an alternative to `file`, but I am not sure if I want to make the target device configurable.

I also dislike that we have 'scsi = true` instead of a _bus_ parameter as an enum.

**Comment by Vanuan** [comment]
Let me explain my use case. My theory was that terraform would help me to build infrastructure from the ground up:

1. Setup storage level with "pet" VMs on Ceph
a. Create Ceph VMs for each block device
b. Provide block devices to VMs
c. Configure Ceph cluster
2. Setup "cattle" VMs to deploy apps in containers
a. Setup Kubernetes/Swarm workers
b. Provide persistent storage to Kubernetes/Swarm workers

Well, it looks like the tooling is not there yet. Or my use case is unusual?

**Comment by MalloZup** [comment]
@Vanuan  hi can you try this out : 
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/examples/xslt/main.tf

i think it will work for you.

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/domain.html.markdown#altering-libvirts-generated-domain-xml-definition

**Comment by MalloZup** [comment]
this can be used with xslt. closing

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/670
