### ISSUE TITLE
Wait for Cloud-Init To Complete

### ISSUE THREAD

**Issue by kjenney** [dmacvicar/terraform-provider-libvirt#449]
#  Version Reports:

### Distro  version of host:

``` 
cat /etc/*release | grep PRETTY_NAME
PRETTY_NAME="Ubuntu 18.04.1 LTS"
```

### Terraform Version Report
```
terraform --version
Terraform v0.11.8
+ provider.libvirt (unversioned)
+ provider.template v1.0.0
```

### Libvirt version

```
virsh --version
4.0.0
```

### terraform-provider-libvirt plugin version (git-hash)

```0.5.0 (Downloaded binary from releases)```
___
# Description of Issue/Question

I've got cloud-init setup to install an Ansible playbook on the VM. Is there any way to wait until the cloud-init script has completed before outputting values?

___
# Additional Infos:

SELinux is disabled, ufw is inactive. Nothing special about my config.

**Comment by MalloZup** [comment]
Hi ! Check this out https://github.com/hashicorp/packer/issues/2639. Adding this would make the codebase rely on unstable 3party changes, an would impact much the codebase for this.
You can solve this e.g in your workflow with a remote exec and looping.p

**Comment by MalloZup** [comment]
@kjenney are you satisfied with the answer more or less ? to me we can close this because in a realistic world you can use `remote-exec` and wait for it or doing other workflow around the `core`.

In the terraform-libvirt part i see this really far away from a future implementation ( is not what i would prioritize as high, imho).

feel free to ask any add info

**Comment by MalloZup** [comment]
Closing for additional question feel free to join the gitter chat! Thx
