### ISSUE TITLE
Enhancement: ability NOT to configure a balloon device

### ISSUE THREAD

**Issue by mykaul** [dmacvicar/terraform-provider-libvirt#511]
It is enabled via libvirt by default, but without anyone managing it, it's not very useful.
To disable it:
```
<memballoon model='none'/>
```

**Comment by dmacvicar** [comment]
Disabling it will result in another issue opened to implement being able to enable it.

Enabled does not hurt, and allows to start using it from the host at any moment. So I think it does not make sense to disable it if the default does has relevant disadvantages.

**Comment by mykaul** [comment]
It's enabled by default, all you need to add is a disable option.
Enabling doesn't hurt, so is disabling it. There isn't anyone that can use it - the only mgmt applications I'm aware of that use it are oVirt and potentially OpenStack (Proxmox?) and non of them run directly against VMs running directly via libvirt and not via their own mgmt agents.

The idea in this issue (and related, similar) is to get to a feature parity with the vagrant libvirt provider.

**Comment by dmacvicar** [comment]
> is to get to a feature parity with the vagrant libvirt provider.

I don't understand. The same feature in the vagrant provider was also opened by you and is still open (https://github.com/vagrant-libvirt/vagrant-libvirt/issues/945).

>all you need to add is a disable option

If it is so trivial, we would welcome a Pull Request from you. As you mention consistency between both projects, please refer to the same accepted PR in vagrant-libvirt once you open one here.

Feel free to cite this issue in the PR, so that we can re-read the original motivation and discussion when reading it.
