### ISSUE TITLE
get rid of "github.com/mitchellh/packer" and substitute it with a right library which generate uuid

### ISSUE THREAD

**Issue by KateGo520** [dmacvicar/terraform-provider-libvirt#770]
## Background
The `packer` has already renamed it’s import path from "github.com/mitchellh/packer" to "github.com/hashicorp/packer".
But `dmacvicar/terraform-provider-libvirt` still used the old path:
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/go.mod#L12
```
github.com/mitchellh/packer v1.3.2
```
When you use the old path "github.com/mitchellh/packer" to import the `packer`, it will be very easy to reintroduce `packer through the import statements "import github.com/hashicorp/packer" in the go source file of `packer`.
https://github.com/hashicorp/packer/blob/v1.3.2/common/step_http_server.go#L11 
```
package common
import (
	"github.com/hashicorp/packer/helper/common"
	"github.com/hashicorp/packer/helper/multistep"
	"github.com/hashicorp/packer/packer"
)…
```
The "github.com/hashicorp/packer" and "github.com/mitchellh/packer" are the same repos. This will work in isolation, bring about potential risks and problems.

So, why not get rid of the old import path "github.com/mitchellh/packer ", use "github.com/hashicorp/packer" instead.

## Solution
Replace all the old import paths, change `"github.com/mitchellh/packer"` to `"github.com/hashicorp/packer"`.
Where did you import it: https://github.com/dmacvicar/terraform-provider-libvirt/search?q=github.com%2Fmitchellh%2Fpacker&unscoped_q=github.com%2Fmitchellh%2Fpacker

**Comment by KateGo520** [comment]
@dmacvicar  @MalloZup  Could you help me review this issue? Thx :p

**Comment by MalloZup** [comment]
@KateGo520  hi thx for your issue.

I have researched a bit today,and here are my thoughts resumed:

1) We don't need packer import, instead we should use `https://github.com/google/uuid` which is more RFC compliant


see other providers:

https://github.com/terraform-providers/terraform-provider-azuredevops/blob/e24bb81ffa64d7f2e0d201fbd7166e7ddcaa12e0/azuredevops/internal/utils/testhelper/dataGenerator.go#L3
https://github.com/terraform-providers/terraform-provider-aws/blob/d148d85330ff4cc95700043d8e6947fa71db7f2f/go.sum#L268


The reason behind this is because we are importing `packer` only for generating `uuid` which is wrong conceptually, because  packer is intended to do something else.

So I guess the fix should be this, to pickup a right UUID library which does the job which the import was  doing and replace it.

thx for the issue. If you want to work on this I can guide you more  but it should be a easy-fix.

**Comment by MalloZup** [comment]
we are using the UUID generation for example here,

**Comment by MalloZup** [comment]
and here https://github.com/dmacvicar/terraform-provider-libvirt/blob/b7dab08a9194e388a7f043a1ab7fe60d241b50e5/libvirt/cloudinit_def.go#L120

**Comment by KateGo520** [comment]
Get rid of "github.com/mitchellh/packer" and substitute it with a right library which generate uuid, that sounds good. Thanks for your efforts and feedback. @MalloZup
