### ISSUE TITLE
Allow to define networks resources

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#8]
No mockup yet...

```hcl
resource "libvirt_network" "mynetwork" {

}
```

**Comment by fisabelle** [comment]
Hum I see... this currently limit the usability of this project. I might be able to assist a little..

So when defining the network, it would also be important for me to be able to use bridge that weren't necessarily created by libvirt.

For instance in my current setup I have 1 manually defined bridge and the 'default' NAT bridge.
However, the net-list only shows the libvirt managed bridges:
[root@lin41-hs20 vmstore]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes

But I can still build VMs with the GUI that use  my custom (virbr1)  bridge:

  <interface type='bridge'>
      <mac address='52:54:00:e0:8f:95'/>
      <source bridge='virbr1'/>
      <target dev='vnet0'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <interface type='network'>
      <mac address='52:54:00:be:61:69'/>
      <source network='default' bridge='virbr0'/>
      <target dev='vnet1'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
    </interface>

==
If would be good to be able to define both 'network' and 'bridge' interfaces and be able to use
either:
 network_interface {
    network = "default"
  }
or
 network_interface {
    bridge = "virbr1"
  }
to define the interfaces.

That being said, without the IP address of the target, (since the "default" interface gets its IP through DHCP) it's a bit hard to set the 'file' provisioner to do useful stuff, since the 'connection' can't really be setup.

Is there currently a solution to move file to the VM image ?
Thank you.

**Comment by dmacvicar** [comment]
Is the usecase of creating a network interface directly attached to a bridge a common scenario?

```
iface --> network
iface --> bridge
```

If I want my VMs to access a physical interface normally I create an interface attached to a network and I attach the network to a bridge (using the `bridge` element in the `network` [description](http://libvirt.org/formatnetwork.html) . That way I always think in term of networks.

```
iface -> network
iface -> network -> bridge
```

Is there any advantage of doing it directly?

**Comment by fisabelle** [comment]
> Is the usecase of creating a network interface directly attached to a bridge a common scenario?
I don't know, currently, when using virt-manager (1.2.1 on CentOS7) to create networks, it won't allow you to create the type of host-bridge network you refer to. So I end up following http://wiki.libvirt.org/page/Networking#Guest_configuration_2 

> Is there any advantage of doing it directly?
If I can figure out how to set the host-bridge as a libvirt virtual network as you indicate, it would be ok for me.

**Comment by flavio** [comment]
JFYI, I'm working on this topic together with @inercia. We want to be able to define a "network" resource using NAT + DHCP and be able to specify static DHCP entries. I'll keep you posted.

**Comment by inercia** [comment]
> JFYI, I'm working on this topic together with @inercia. We want to be able to define a "network" resource using NAT + DHCP and be able to specify static DHCP entries. I'll keep you posted.

... it would be something like [this](https://github.com/inercia/libvirt-go/commit/f40d7c2b2a79fb0b1f4b615b796be66ee2a438c0), probably with also a `RemoveHost`...

**Comment by dmacvicar** [comment]
@inercia @flavio I don't think you need to AddHost/Remove host. Generating the right xml for the network resource may be suficient.

Using the Add/Remove functions becomes useful if you want to implement a very granular ResourceUpdate.

Do you need to add and remove hosts after you define the resource?

**Comment by fisabelle** [comment]
FYI.

Currently, my workaround is to set the mac address in the resource and define a static DHCP mapping on the bridge network. This allows be to use a corresponding known IP addresses.

network_interface {
    network = "host-bridge2"
    mac= "52:54:00:A1:A3:60"
  }

  connection {
   host = "10.9.64.60"
  }

so whatever you do, as long as I can still use my method, I'll be ok.

**Comment by inercia** [comment]
> @inercia @flavio I don't think you need to AddHost/Remove host. Generating the right xml for the network resource may be suficient.

> Using the Add/Remove functions becomes useful if you want to implement a very granular ResourceUpdate.

> Do you need to add and remove hosts after you define the resource?

Well, our plan was to define a _network_ resource and then connect each domain to it. Something like this:

```
resource "libvirt_network" "our_net" {
  name = "our_net"
  domain = "k8s.local"
  addresses = "10.10.0.0/24"
}

resource "libvirt_domain" "master" {
  name = "host_a"
  disk {
    volume_id = "${libvirt_volume.salt_volume.id}"
  }
  network_interface {
    network_id = "${libvirt_network.our_net.id}"

    hostname = "master"
    address = "10.10.0.3"
    mac = "AA:BB:CC:11:22:22"
    wait_for_lease = 1
  }
}
```

For doing so, we would need first to create a basic network (with the help of _libvirt-go_ and a XML description) and then add one by one all the network interfaces, and this part need that level of granularity...

**Comment by dmacvicar** [comment]
I think this one can be closed already.
